apiVersion: v1
kind: Service
metadata:
  name: flask-kubernetes-example
spec:
  type: NodePort
  ports:
  - name: web
    port: 5001
    targetPort: 5000
  - name: debug
    port: 4445
    targetPort: 4444
  selector:
    app: flask-kubernetes-example